### ISSUE TITLE
diff --git ??

### ISSUE THREAD

**Issue by heaterC** [johannesjh/crrcsim-mac#1]
Hi there! To apply the patch, you propose
diff --git a/src/mod_misc/filesystools.cpp b/src/mod_misc/filesystools.cpp

I'm on macOS 10.12.1, and I can't get to work the option "--git" (maybe due to my lack of experience, but I'd still love to compile crrcsim, there's even a new 0.9.13 out). Thanks for any help.

**Comment by johannesjh** [comment]
Hi! Thank you for your interest! 

I believe your question involves a misunderstanding rather than a bug. 
Have you tried copy-pasting everything from line 47 to 113 into the Terminal application? 

More detailed explanation: In the `build-instructions.sh` shell script, everything from line 47 down to line 113 is one single command. The command makes use of the [heredoc notation](http://www.tldp.org/LDP/abs/html/here-docs.html) so that everything between `<< 'EOF'` and `EOF` is a single, long, multi-line string given as argument to the patch command. Thus `diff --git` is not a command to be executed, it is only part of that long string - or, more specifically, part of the patch that is provided as argument to the patch command.

**Comment by heaterC** [comment]
Hi, thanks a lot for your quick answer. Actually, what you describe is what I did first and it led to a different error:

can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/mod_misc/filesystools.cpp b/src/mod_misc/filesystools.cpp
|index b20eb3a..d085eb7 100644
|--- a/src/mod_misc/filesystools.cpp
|+++ b/src/mod_misc/filesystools.cpp
--------------------------

This is what made me think there must be some kind of „special“ diff command, since there is no physical path „a“ or „b“ inside the crrcsim-0.9.12 directory. I admit that I did not follow your instructions further up the script and I unpacked the tar.gz with the Finder, but I can’t think of how that should produce a different result?

If you have any idea, I’d be grateful. Actually, have you ever tried compiling the new 0.9.13? Cheers, Boris

**Comment by johannesjh** [comment]
hi! thanks for giving it a try. I think there is an error in my script. Can you try applying the patch using `patch -p1 -R`?

PS, 
I currently do not have macports installed on my machine, so while the above command seemed successful in applying the patch, I could not try out if everything builds successfully.

**Comment by johannesjh** [comment]
by the way, you are welcome to fork and/or create pull requests to further automate the script (as for now, the script is basically nothing more than a few notes I took while doing the compilation). also, if you'd get it to work with CRRCSim 0.9.13, that would be awesome!

**Comment by johannesjh** [comment]
one more comment: I just had the idea that fully automated and builds that can more easily be reproduced (e.g., without having to mess around with macports) could be achieved using Vagrant. E.g., 

```
vagrant init jhcook/macos-sierra
vagrant up --provider virtualbox
```

...and the rest of the build script would run inside vagrant.

**Comment by heaterC** [comment]
Great ideas! I am just reading for the first time about Vagrant (I am no software developer). Seems a cool tool if it really works that simple. Then I've never done any forks or pull requests, but maybe a shell script would be the best for a first try. ;-) You see, I would really struggle heavily to make a new version of crrcsim work, even more on Sierra... BUT: your `patch -p1 -R` worked perfectly, so I am on my way again to make this script work! Thanks for now.

**Comment by johannesjh** [comment]
Any updates, did the build work correctly?

EDIT: I also tried the build process again, but I could not get it to work. I correspondingly updated the description of this repository.

**Comment by johannesjh** [comment]
I will close this issue and archive this repository
